load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_repl_syntax",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:shlex",
        "fbsource//third-party/rust:unicode-segmentation",
        "fbsource//third-party/rust:unicode-width",
    ],
)
