load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native

prelude.export_file(
    name = "container_run.sh",
    visibility = ["PUBLIC"],
)
