#!/bin/sh
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is dual-licensed under either the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree or the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree. You may select, at your option, one of the
# above-listed licenses.

# Launcher for the `container_run` rule (prelude//container:container_run.bzl).
#
#   /bin/sh container_run.sh [OPTION VALUE]... -- ARGV0 [ARGS...]
#
# On macOS this runs ARGV0 inside a Linux container, using Apple's `container`
# CLI by default. Everywhere else it execs ARGV0 directly, so a wrapped target
# keeps working on Linux hosts and as a tool inside (remote) actions. Set
# BUCK_CONTAINER_RUN=auto|always|never to override the choice. The options are
# generated by the rule and are not a user-facing interface. See
# docs/users/how_tos/container_run.md.
#
# Portability: this must run under macOS /bin/sh (bash 3.2 in POSIX mode),
# dash and busybox ash. Do not use arrays, `local`, `echo` (use printf),
# `set -e`, or `case` inside $(...) (bash 3.2 cannot parse it). Never append to
# "$@", or call a function with a growing argument list, in a loop: both are
# quadratic in bash 3.2. Container options are collected as one quoted string
# and expanded by a single `eval` at the end.
#
# Every variable is prefixed with `_cr_`: assigning to a variable that came from
# the environment changes what the program sees, so the launcher must not
# share names with the program's environment.

set -u

die() {
    printf 'container_run: %s\n' "$1" >&2
    exit 125
}

note() {
    printf 'container_run: note: %s\n' "$1" >&2
}

# quote VALUE: set $_cr_quoted to VALUE as a single-quoted shell word.
quote() {
    _cr_q_in=$1 _cr_quoted=''
    while :; do
        case $_cr_q_in in
            *\'*)
                _cr_quoted=$_cr_quoted${_cr_q_in%%\'*}"'\\''"
                _cr_q_in=${_cr_q_in#*\'}
                ;;
            *) break ;;
        esac
    done
    _cr_quoted="'$_cr_quoted$_cr_q_in'"
}

# add VAR VALUE...: append each VALUE, quoted, to the string held in $VAR.
add() {
    _cr_add_var=$1
    shift
    for _cr_add_v in "$@"; do
        quote "$_cr_add_v"
        eval "$_cr_add_var=\"\$$_cr_add_var \$_cr_quoted\""
    done
}

# show ARG...: print a command line to stderr (BUCK_CONTAINER_RUN_VERBOSE=1).
# The quoting is inlined: calling `quote` here, with every argument in "$@",
# would be quadratic in bash 3.2.
show() {
    printf 'container_run: running:' >&2
    for _cr_a in "$@"; do
        _cr_s=''
        while :; do
            case $_cr_a in
                *\'*)
                    _cr_s=$_cr_s${_cr_a%%\'*}"'\\''"
                    _cr_a=${_cr_a#*\'}
                    ;;
                *) break ;;
            esac
        done
        printf " '%s'" "$_cr_s$_cr_a" >&2
    done
    printf '\n' >&2
}

# Helpers are also looked up at their macOS paths: a test's `env` may set a
# PATH without them.
sysctl_n() {
    if command -v sysctl >/dev/null 2>&1; then
        sysctl -n "$1" 2>/dev/null
    else
        /usr/sbin/sysctl -n "$1" 2>/dev/null
    fi
}

physical_pwd() {
    /bin/pwd -P 2>/dev/null || pwd -P
}

_cr_mode=${BUCK_CONTAINER_RUN:-auto}
case $_cr_mode in
    auto)
        _cr_os=$(uname -s 2>/dev/null || /usr/bin/uname -s 2>/dev/null)
        if [ "$_cr_os" = Darwin ]; then _cr_mode=always; else _cr_mode=never; fi
        ;;
    always | never) ;;
    *) die "BUCK_CONTAINER_RUN must be auto, always or never (got '$_cr_mode')" ;;
esac

_cr_target=this _cr_cli=container _cr_flavor=apple _cr_image='' _cr_platform=''
_cr_root='' _cr_cpus='' _cr_memory='' _cr_user='' _cr_envs='' _cr_detach=0
while :; do
    [ "$#" -gt 0 ] || die "internal error: missing '--' before the command"
    _cr_o=$1
    shift
    case $_cr_o in
        --) break ;;
        --target | --cli | --flavor | --image | --platform | --project-root | --cpus | --memory | \
            --mount | --env | --env-passthrough | --run-arg)
            [ "$#" -gt 0 ] || die "internal error: option '$_cr_o' needs a value"
            _cr_v=$1
            shift
            ;;
        *) die "internal error: unknown option '$_cr_o'" ;;
    esac
    if [ "$_cr_mode" = never ]; then
        # Running directly: only `--env` matters, so that the rule's `env`
        # behaves the same on every host.
        if [ "$_cr_o" = --env ]; then
            case ${_cr_v%%=*} in
                '' | [0-9]* | *[!A-Za-z0-9_]*) die "internal error: bad variable name in '--env $_cr_v'" ;;
            esac
            add _cr_envs "$_cr_v"
        fi
        continue
    fi
    case $_cr_o in
        --target) _cr_target=$_cr_v ;;
        --cli) _cr_cli=$_cr_v ;;
        --flavor) _cr_flavor=$_cr_v ;;
        --image) _cr_image=$_cr_v ;;
        --platform) _cr_platform=$_cr_v ;;
        --project-root) _cr_root=$_cr_v ;;
        --cpus) _cr_cpus=$_cr_v ;;
        --memory) _cr_memory=$_cr_v ;;
        --mount)
            case $_cr_v in
                /*) ;;
                *) die "internal error: mount '$_cr_v' is not an absolute path" ;;
            esac
            case $_cr_v in
                *:*) die "mount '$_cr_v' contains ':', which the container CLI cannot mount" ;;
            esac
            if [ -e "$_cr_v" ]; then
                add _cr_user --volume "$_cr_v:$_cr_v"
            else
                note "skipping mount '$_cr_v': it does not exist on this machine"
            fi
            ;;
        # Only the name: the CLI copies the value from this process's
        # environment (and skips unset names), so values never appear in argv.
        --env-passthrough) add _cr_user --env "$_cr_v" ;;
        --env) add _cr_user --env "$_cr_v" ;;
        --run-arg)
            add _cr_user "$_cr_v"
            case $_cr_v in -d | --detach) _cr_detach=1 ;; esac
            ;;
    esac
done
[ "$#" -gt 0 ] || die "internal error: no command to run"

if [ "$_cr_mode" = never ]; then
    # Apply `env` with env(1) rather than shell assignments, which fail for
    # readonly shell variables such as UID and change special ones such as
    # RANDOM. env(1) would take a command that contains '=' for an assignment,
    # so such a command goes through sh.
    if [ -n "$_cr_envs" ]; then
        _cr_env=/usr/bin/env
        [ -x "$_cr_env" ] || _cr_env='env'
        case $1 in
            *=*) eval "set -- \"\$_cr_env\" $_cr_envs /bin/sh -c 'exec \"\$@\"' sh \"\$@\"" ;;
            *) eval "set -- \"\$_cr_env\" $_cr_envs \"\$@\"" ;;
        esac
    fi
    if [ "${BUCK_CONTAINER_RUN_VERBOSE:-}" = 1 ]; then show "$@"; fi
    exec "$@"
fi

case $_cr_flavor in
    apple | docker) ;;
    *) die "internal error: unknown CLI flavor '$_cr_flavor'" ;;
esac
[ -n "$_cr_image" ] || die "internal error: no image"

# Locate the CLI. Processes started from an IDE, and the buck2 daemon (which
# runs tests), often lack /usr/local/bin and /opt/homebrew/bin on PATH.
_cr_found=''
case $_cr_cli in
    */*) if [ -x "$_cr_cli" ]; then _cr_found=$_cr_cli; fi ;;
    *)
        _cr_found=$(command -v "$_cr_cli" 2>/dev/null) || _cr_found=''
        if [ -z "$_cr_found" ]; then
            for _cr_d in /usr/local/bin /opt/homebrew/bin; do
                if [ -x "$_cr_d/$_cr_cli" ]; then
                    _cr_found=$_cr_d/$_cr_cli
                    break
                fi
            done
        fi
        ;;
esac
if [ -z "$_cr_found" ]; then
    if [ "$_cr_flavor" = apple ]; then
        die "'$_cr_cli' was not found on PATH or in /usr/local/bin or /opt/homebrew/bin.
  $_cr_target is a Linux program. On macOS it runs in a lightweight Linux VM using
  Apple's container CLI (Apple silicon, macOS 26 or later, container 1.0 or later).
  Install the signed package from https://github.com/apple/container/releases,
  then run: container system start
  If the program also runs on macOS (for example a script), set
  BUCK_CONTAINER_RUN=never to run it directly."
    fi
    die "'$_cr_cli' was not found on PATH or in /usr/local/bin or /opt/homebrew/bin.
  $_cr_target is a Linux program; this repo runs it with a Docker-compatible CLI
  (Docker Desktop, OrbStack, Colima or Podman). Install one. If the program also
  runs on macOS (for example a script), set BUCK_CONTAINER_RUN=never to run it
  directly."
fi
_cr_cli=$_cr_found

# The project root is mounted at the same path inside the container, so the
# absolute paths buck2 renders stay valid there. Inside actions it arrives as
# '.' or '../..'; it may carry a trailing '/'; and the current directory may
# have been reached through symlinks (/tmp -> /private/tmp) or, on a
# case-insensitive file system, spelled differently, so compare physical paths.
# (bash's `pwd -P` keeps an inherited $PWD spelling; /bin/pwd does not.)
_cr_root_p=$(cd -P -- "${_cr_root:-.}" 2>/dev/null && physical_pwd) ||
    die "project root '$_cr_root' is not a directory"
case $_cr_root in
    /*) ;;
    *) _cr_root=$_cr_root_p ;;
esac
while :; do
    case $_cr_root in
        ?*/) _cr_root=${_cr_root%/} ;;
        *) break ;;
    esac
done
case $_cr_root in
    *:*) die "the project root '$_cr_root' contains ':', which the container CLI cannot mount; move the checkout" ;;
esac
_cr_here=$(physical_pwd) || die "cannot determine the current directory"
case $_cr_here/ in
    "$_cr_root_p"/*) _cr_inside=1 _cr_workdir=$_cr_root${_cr_here#"$_cr_root_p"} ;;
    *)
        _cr_inside=0 _cr_workdir=$_cr_root
        note "'$_cr_here' is not inside the project root '$_cr_root'; running in '$_cr_root' instead"
        ;;
esac

_cr_entry=$1
shift
case $_cr_entry in
    /*) ;;
    */*)
        [ "$_cr_inside" = 1 ] || die "cannot run '$_cr_entry' in the container: the current directory '$_cr_here' is outside the project root '$_cr_root'"
        _cr_entry=$_cr_workdir/$_cr_entry
        ;;
    *) ;; # A bare name is looked up on the image's PATH.
esac

# `container system start` registers the API server with launchd from a plist
# outside ~/Library/LaunchAgents, so the registration is gone after a reboot.
# This is the same probe `container system status` uses.
if [ "$_cr_flavor" = apple ]; then
    _cr_launchctl=''
    if command -v launchctl >/dev/null 2>&1; then
        _cr_launchctl=launchctl
    elif [ -x /bin/launchctl ]; then
        _cr_launchctl=/bin/launchctl
    fi
    if [ -n "$_cr_launchctl" ] && ! "$_cr_launchctl" list com.apple.container.apiserver >/dev/null 2>&1; then
        printf 'container_run: starting container services (container system start)\n' >&2
        "$_cr_cli" system start --disable-kernel-install </dev/null >&2 ||
            die "could not start the container services. Run 'container system start' in a terminal (on first use it offers to install a Linux kernel), then try again."
    fi
fi

# The Apple CLI defaults to 4 CPUs and 1 GiB of memory per container, which
# gets real programs OOM-killed. "host" sizes the container like the Mac.
if [ "$_cr_cpus" = host ]; then
    _cr_cpus=''
    if [ "$_cr_flavor" = apple ]; then _cr_cpus=$(sysctl_n hw.ncpu); fi
    case $_cr_cpus in
        '' | *[!0-9]*) _cr_cpus='' ;;
    esac
fi
if [ "$_cr_memory" = host ]; then
    _cr_memory=''
    if [ "$_cr_flavor" = apple ]; then
        _cr_b=$(sysctl_n hw.memsize)
        case $_cr_b in
            '' | *[!0-9]*) ;;
            *) _cr_memory=$((_cr_b / 2097152))M ;; # Half of physical memory, in MiB.
        esac
    fi
fi

# Named, so that the watchdog below can stop it.
_cr_name=buck2-$$-$(PATH=$PATH:/bin:/usr/bin date +%s 2>/dev/null)

_cr_pre=''
add _cr_pre run --rm -i --name "$_cr_name"
# -t only when stdin, stdout and stderr are all terminals: with -t the CLI
# merges stderr into the pty, so `2>file` would silently stop working.
if [ -t 0 ] && [ -t 1 ] && [ -t 2 ]; then
    case ${TERM:-} in
        xterm | xterm-256color | xterm-color | screen | screen-256color | tmux | tmux-256color | \
            vt100 | vt220 | linux | dumb) _cr_term=$TERM ;;
        *) _cr_term=xterm-256color ;; # e.g. xterm-kitty and xterm-ghostty are not in most images.
    esac
    add _cr_pre -t --env "TERM=$_cr_term"
fi
# Keep image-pull progress out of redirected stderr.
if [ ! -t 2 ]; then
    if [ "$_cr_flavor" = apple ]; then add _cr_pre --progress none; else add _cr_pre --quiet; fi
fi
add _cr_pre --init
if [ -n "$_cr_platform" ]; then add _cr_pre --platform "$_cr_platform"; fi
# Label the container with the target, to make leftovers easy to identify. The
# CLI rejects values that contain '=' and labels longer than 4096 bytes.
case $_cr_target in
    *=*) ;;
    *) if [ "${#_cr_target}" -le 4000 ]; then add _cr_pre --label "buck2.target=$_cr_target"; fi ;;
esac
add _cr_pre --volume "$_cr_root:$_cr_root" --workdir "$_cr_workdir"
if [ -n "$_cr_cpus" ]; then add _cr_pre --cpus "$_cr_cpus"; fi
if [ -n "$_cr_memory" ]; then add _cr_pre --memory "$_cr_memory"; fi
add _cr_pre --env BUCK_RUN_BUILD_ID

# Per-invocation flags come after the rule's, so that they win for
# single-valued options.
_cr_extra=''
if [ -n "${BUCK_CONTAINER_RUN_ARGS:-}" ]; then
    set -f
    for _cr_a in $BUCK_CONTAINER_RUN_ARGS; do
        add _cr_extra "$_cr_a"
        case $_cr_a in -d | --detach) _cr_detach=1 ;; esac
    done
    set +f
fi
# `--` stops the CLI from parsing the program's arguments as its own options
# (for example '---' or '--generate-completion-script').
add _cr_extra --entrypoint "$_cr_entry" -- "$_cr_image"

if [ "${BUCK_CONTAINER_RUN_VERBOSE:-}" = 1 ]; then
    eval "show \"\$_cr_cli\" $_cr_pre $_cr_user $_cr_extra \"\$@\""
fi

# If the CLI is killed, the container keeps running in its VM: buck2 SIGKILLs
# the process group of a cancelled or timed-out test, and closing a terminal
# sends SIGHUP, neither of which the CLI can forward. This watchdog stops the
# container once this process (the CLI, after `exec`) is gone; after a normal
# exit `--rm` has already removed it and the stop does nothing. The watchdog
# must leave our process group to survive it being killed: bash (macOS's
# /bin/sh) does that for a background job under `set -m` without touching the
# terminal; other shells use setsid(1) where it exists. Its output goes to
# /dev/null so that it does not hold buck2's pipes open, and it gets the
# system directories on PATH because a test's `env` may replace PATH. Detached
# containers (`-d`) are left alone.
if [ "$_cr_detach" = 0 ]; then
    # shellcheck disable=SC2016 # Expanded by the watchdog's shell.
    _cr_wd='trap "" HUP INT TERM
PATH=$PATH:/bin:/usr/bin
while kill -0 "$1" 2>/dev/null; do sleep 1 || exit 0; done
exec "$2" stop "$3"'
    _cr_setsid=$(command -v setsid 2>/dev/null) || _cr_setsid=/usr/bin/setsid
    if [ -n "${BASH_VERSION-}" ]; then
        set -m
        /bin/sh -c "$_cr_wd" sh "$$" "$_cr_cli" "$_cr_name" </dev/null >/dev/null 2>&1 &
        set +m
    elif [ -x "$_cr_setsid" ]; then
        "$_cr_setsid" /bin/sh -c "$_cr_wd" sh "$$" "$_cr_cli" "$_cr_name" </dev/null >/dev/null 2>&1 &
    else
        # Survives SIGHUP, but not the process group being killed.
        /bin/sh -c "$_cr_wd" sh "$$" "$_cr_cli" "$_cr_name" </dev/null >/dev/null 2>&1 &
    fi
fi

eval "exec \"\$_cr_cli\" $_cr_pre $_cr_user $_cr_extra \"\$@\""
