#!/bin/sh
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is dual-licensed under either the MIT license found in the
# LICENSE-MIT file in the root directory of this source tree or the Apache
# License, Version 2.0 found in the LICENSE-APACHE file in the root directory
# of this source tree. You may select, at your option, one of the
# above-listed licenses.

# Launcher for the `container_run` rule (prelude//container:container_run.bzl).
#
#   /bin/sh container_run.sh [OPTION VALUE]... -- ARGV0 [ARGS...]
#
# On macOS this runs ARGV0 inside a Linux container, using Apple's `container`
# CLI by default. Everywhere else it execs ARGV0 directly, so a wrapped target
# keeps working on Linux hosts and as a tool inside (remote) actions. Set
# BUCK_CONTAINER_RUN=auto|always|never to override the choice. The options are
# generated by the rule and are not a user-facing interface. See
# docs/users/how_tos/container_run.md.
#
# Portability: this must run under macOS /bin/sh (bash 3.2 in POSIX mode),
# dash and busybox ash. Do not use arrays, `local`, `echo` (use printf),
# `set -e`, or `case` inside $(...) (bash 3.2 cannot parse it). Never append to
# "$@" in a loop, which is quadratic in bash 3.2: container options are
# collected as one quoted string and expanded by a single `eval` at the end.

set -u

die() {
    printf 'container_run: %s\n' "$1" >&2
    exit 125
}

note() {
    printf 'container_run: note: %s\n' "$1" >&2
}

# quote VALUE: set $quoted to VALUE as a single-quoted shell word.
quote() {
    q_in=$1 quoted=
    while :; do
        case $q_in in
            *\'*)
                quoted=$quoted${q_in%%\'*}"'\\''"
                q_in=${q_in#*\'}
                ;;
            *) break ;;
        esac
    done
    quoted="'$quoted$q_in'"
}

# add VAR VALUE...: append each VALUE, quoted, to the string held in $VAR.
add() {
    add_var=$1
    shift
    for add_v in "$@"; do
        quote "$add_v"
        eval "$add_var=\"\$$add_var \$quoted\""
    done
}

# show ARG...: print a command line to stderr (BUCK_CONTAINER_RUN_VERBOSE=1).
show() {
    shown=
    for a in "$@"; do
        quote "$a"
        shown="$shown $quoted"
    done
    printf 'container_run: running:%s\n' "$shown" >&2
}

sysctl_n() {
    if command -v sysctl >/dev/null 2>&1; then
        sysctl -n "$1" 2>/dev/null
    else
        /usr/sbin/sysctl -n "$1" 2>/dev/null
    fi
}

mode=${BUCK_CONTAINER_RUN:-auto}
case $mode in
    auto)
        if [ "$(uname -s 2>/dev/null)" = Darwin ]; then mode=always; else mode=never; fi
        ;;
    always | never) ;;
    *) die "BUCK_CONTAINER_RUN must be auto, always or never (got '$mode')" ;;
esac

target=this cli=container flavor=apple image='' platform='' root='' cpus='' memory=''
user=''
while :; do
    [ $# -gt 0 ] || die "internal error: missing '--' before the command"
    o=$1
    shift
    case $o in
        --) break ;;
        --target | --cli | --flavor | --image | --platform | --project-root | --cpus | --memory | \
            --mount | --env | --env-passthrough | --run-arg)
            [ $# -gt 0 ] || die "internal error: option '$o' needs a value"
            v=$1
            shift
            ;;
        *) die "internal error: unknown option '$o'" ;;
    esac
    if [ "$mode" = never ]; then
        # Running directly: only `--env` matters, so that the rule's `env`
        # behaves the same on every host.
        if [ "$o" = --env ]; then
            k=${v%%=*}
            case $k in
                '' | [0-9]* | *[!A-Za-z0-9_]*) die "internal error: bad variable name in '--env $v'" ;;
            esac
            eval "$k=\${v#*=}"
            # shellcheck disable=SC2163 # Exports the variable named by $k.
            export "$k"
        fi
        continue
    fi
    case $o in
        --target) target=$v ;;
        --cli) cli=$v ;;
        --flavor) flavor=$v ;;
        --image) image=$v ;;
        --platform) platform=$v ;;
        --project-root) root=$v ;;
        --cpus) cpus=$v ;;
        --memory) memory=$v ;;
        --mount)
            case $v in
                /*) ;;
                *) die "internal error: mount '$v' is not an absolute path" ;;
            esac
            case $v in
                *:*) die "mount '$v' contains ':', which the container CLI cannot mount" ;;
            esac
            if [ -e "$v" ]; then
                add user --volume "$v:$v"
            else
                note "skipping mount '$v': it does not exist on this machine"
            fi
            ;;
        # Only the name: the CLI copies the value from this process's
        # environment (and skips unset names), so values never appear in argv.
        --env-passthrough) add user --env "$v" ;;
        --env) add user --env "$v" ;;
        --run-arg) add user "$v" ;;
    esac
done
[ $# -gt 0 ] || die "internal error: no command to run"

if [ "$mode" = never ]; then
    if [ "${BUCK_CONTAINER_RUN_VERBOSE:-}" = 1 ]; then show "$@"; fi
    exec "$@"
fi

case $flavor in
    apple | docker) ;;
    *) die "internal error: unknown CLI flavor '$flavor'" ;;
esac
[ -n "$image" ] || die "internal error: no image"

# Locate the CLI. Processes started from an IDE, and the buck2 daemon (which
# runs tests), often lack /usr/local/bin and /opt/homebrew/bin on PATH.
found=
case $cli in
    */*) if [ -x "$cli" ]; then found=$cli; fi ;;
    *)
        found=$(command -v "$cli" 2>/dev/null) || found=
        if [ -z "$found" ]; then
            for d in /usr/local/bin /opt/homebrew/bin; do
                if [ -x "$d/$cli" ]; then
                    found=$d/$cli
                    break
                fi
            done
        fi
        ;;
esac
if [ -z "$found" ]; then
    if [ "$flavor" = apple ]; then
        die "'$cli' was not found on PATH or in /usr/local/bin or /opt/homebrew/bin.
  $target is a Linux program. On macOS it runs in a lightweight Linux VM using
  Apple's container CLI (Apple silicon, macOS 26 or later, container 1.0 or later).
  Install the signed package from https://github.com/apple/container/releases,
  then run: container system start
  To run it directly instead, set BUCK_CONTAINER_RUN=never."
    fi
    die "'$cli' was not found on PATH or in /usr/local/bin or /opt/homebrew/bin.
  $target is a Linux program; this repo runs it with a Docker-compatible CLI
  (Docker Desktop, OrbStack, Colima or Podman). Install one, or set
  BUCK_CONTAINER_RUN=never to run it directly."
fi
cli=$found

# The project root is mounted at the same path inside the container, so the
# absolute paths buck2 renders stay valid there. Inside actions it arrives as
# '.' or '../..'; it may carry a trailing '/'; and the current directory may
# have been reached through symlinks (/tmp -> /private/tmp), so compare
# physical paths.
root_p=$(cd -P -- "${root:-.}" 2>/dev/null && pwd -P) || die "project root '$root' is not a directory"
case $root in
    /*) ;;
    *) root=$root_p ;;
esac
while :; do
    case $root in
        ?*/) root=${root%/} ;;
        *) break ;;
    esac
done
case $root in
    *:*) die "the project root '$root' contains ':', which the container CLI cannot mount; move the checkout or set BUCK_CONTAINER_RUN=never" ;;
esac
here=$(pwd -P 2>/dev/null) || die "cannot determine the current directory"
case $here/ in
    "$root_p"/*) inside=1 workdir=$root${here#"$root_p"} ;;
    *)
        inside=0 workdir=$root
        note "'$here' is not inside the project root '$root'; running in '$root' instead"
        ;;
esac

entry=$1
shift
case $entry in
    /*) ;;
    */*)
        [ "$inside" = 1 ] || die "cannot run '$entry' in the container: the current directory '$here' is outside the project root '$root'"
        entry=$workdir/$entry
        ;;
    *) ;; # A bare name is looked up on the image's PATH.
esac

# `container system start` registers the API server with launchd from a plist
# outside ~/Library/LaunchAgents, so the registration is gone after a reboot.
# This is the same probe `container system status` uses.
if [ "$flavor" = apple ] && command -v launchctl >/dev/null 2>&1 &&
    ! launchctl list com.apple.container.apiserver >/dev/null 2>&1; then
    printf 'container_run: starting container services (container system start)\n' >&2
    "$cli" system start --disable-kernel-install </dev/null >&2 ||
        die "could not start the container services. Run 'container system start' in a terminal (on first use it offers to install a Linux kernel), then try again."
fi

# The Apple CLI defaults to 4 CPUs and 1 GiB of memory per container, which
# gets real programs OOM-killed. "host" sizes the container like the Mac.
if [ "$cpus" = host ]; then
    cpus=
    if [ "$flavor" = apple ]; then cpus=$(sysctl_n hw.ncpu); fi
    case $cpus in
        '' | *[!0-9]*) cpus= ;;
    esac
fi
if [ "$memory" = host ]; then
    memory=
    if [ "$flavor" = apple ]; then
        b=$(sysctl_n hw.memsize)
        case $b in
            '' | *[!0-9]*) ;;
            *) memory=$((b / 2097152))M ;; # Half of physical memory, in MiB.
        esac
    fi
fi

pre=
add pre run --rm -i
# -t only when stdin, stdout and stderr are all terminals: with -t the CLI
# merges stderr into the pty, so `2>file` would silently stop working.
if [ -t 0 ] && [ -t 1 ] && [ -t 2 ]; then
    case ${TERM:-} in
        xterm | xterm-256color | xterm-color | screen | screen-256color | tmux | tmux-256color | \
            vt100 | vt220 | linux | dumb) term=$TERM ;;
        *) term=xterm-256color ;; # e.g. xterm-kitty and xterm-ghostty are not in most images.
    esac
    add pre -t --env "TERM=$term"
fi
# Keep image-pull progress out of redirected stderr.
if [ ! -t 2 ]; then
    if [ "$flavor" = apple ]; then add pre --progress none; else add pre --quiet; fi
fi
add pre --init
if [ -n "$platform" ]; then add pre --platform "$platform"; fi
# Label the container so leaked ones can be found with `container ls -a`. The
# CLI rejects values that contain '=' and labels longer than 4096 bytes.
case $target in
    *=*) ;;
    *) if [ "${#target}" -le 4000 ]; then add pre --label "buck2.target=$target"; fi ;;
esac
add pre --volume "$root:$root" --workdir "$workdir"
if [ -n "$cpus" ]; then add pre --cpus "$cpus"; fi
if [ -n "$memory" ]; then add pre --memory "$memory"; fi
add pre --env BUCK_RUN_BUILD_ID

# Per-invocation flags come last so that they win for single-valued options.
extra=
if [ -n "${BUCK_CONTAINER_RUN_ARGS:-}" ]; then
    set -f
    for a in $BUCK_CONTAINER_RUN_ARGS; do add extra "$a"; done
    set +f
fi
add extra --entrypoint "$entry" "$image"

if [ "${BUCK_CONTAINER_RUN_VERBOSE:-}" = 1 ]; then
    eval "show \"\$cli\" $pre $user $extra \"\$@\""
fi
eval "exec \"\$cli\" $pre $user $extra \"\$@\""
